@startuml 005_ReadingVendorLabelOfHolder
skinparam responseMessageBelowArrow true

title
RequestForWritingLinkIdIntoLtpCausesReadingAirInterfaceCapabilitiesFromCache
end title

participant "External" as external
participant "LILW://v1/write-link-id-into-ltp" as lilw_write
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}/logical-termination-point={uuid}/layer-protocol={local-id}/air-interface-2-0:air-interface-pac/air-interface-capability" as MwdiCapa


external -> lilw_write: {linkId, mountNameA, mountNameB, {planning-data}} (apiKeyAuth)
activate lilw_write
lilw_write -> MwdiCapa: {mountName, uuid, localId } (apiKeyAuth)
MwdiCapa--> lilw_write: {entire AirInterfaceCapabilities from cache}
deactivate lilw_write
@enduml