@startuml 011_RemovingLinkIdFromLtpAndQueue
skinparam responseMessageBelowArrow true

title
RequestForWritingLinkIdIntoLtpCausesRemovingLinkIdFromLtpAndQueue
end title

participant "External" as external
participant "LILW://v1/write-link-id-into-ltp" as lilw_write
participant "LILW://v1/remove-link-id-from-queue-and-ltps" as lilw_remove



external -> lilw_write: {linkId, mountNameA, mountNameB, {planning-data}} (apiKeyAuth)

activate lilw_write 
lilw_write -> lilw_remove: {linkId} (apiKeyAuth)
lilw_remove --> lilw_write: 200 OK
deactivate lilw_write
@enduml