@startuml
start

:Retrieve Entry from Queue;
:reliabilityScore = 0;
group for each AirInterfaceLtp in Site A

    repeat

        group Evaluate LTP in Site A
            :Perform PlanningDataTests;
            :Calculate ltpScoreA;
        end group
            if (ltpScoreA > thresholdValue?) then (Yes)

                if (is Site B reachable?) then (Yes)

                    group for each AirInterfaceLtp in Site B    

                        repeat
                            group Evaluate LTP in Site B
                                :Perform 'PlannedDataTests';
                                :Calculate ltpScoreB;
                            end group
                                if (ltpScoreB > thresholdValue?) then (Yes)
                                    :candidateScore = (ltpScoreA + ltpScoreB) / 2 ;                    
                                    group Cross-Link Tests
                                        :Perform 'Cross-Link Tests';
                                        :Update candidateScore;
                                    end group

                                    if(candidateScore > thresholdValue?) then (Yes)
                                        :Add LTPs from site A and site B with the candidateScore to\nthe list of candidates;
                                    else (No)
                                    endif

                                else (No)

                                endif

                        repeat while (continue with next LTP in B)                
                        -> //no more LTPs in site B//;

                    end group

                else (No)
                    :candidateScore = ltpScoreA;
                    :Add LTP with its candidateScore to list of candidates;
                endif

            else (No)
            endif
    
    
    repeat while (Continue with Next LTP in A)
    -> //no more LTPs in site A//;
end group
    



if (at least one candidate?) then (Yes)
    :bestCandidate -> candidate with greatest ltpScore;
    group for each Ltp of bestCandidate (single LTP or LTP-pair)
        repeat
            if( is the linkId already written \nin a different LTP of this device?) then (Yes)
                if(is this other interface active?) then (Yes)
                    :Send alarm with report result of both LTPs evaluations (?);
                    :Return '409: Conflict' (?) and requeue entry;
                    stop
                else (No)
                    :Remove linkId from this inactive LTP\n(write default value);
                endif

            else(no)      
            endif

            :Write linkId into the bestCandidate LTP;

        repeat while (continue with Ltp of opposite link-end, if given)
    end group
    
    :reliabilityScore = candidateScore of bestCandidate;
    :Assign a priorityBand to the entry based on its reliabilityScore;
    :Return '200' and requeue entry;


else(no)
    :Send Alarm (?);
    :Return 470 (? or 404?) and requeue entry (?);
stop
endif
stop




@enduml
