@startuml
start

:Retrieve Entry from Queue;

group for each AirInterfaceLtp in Device
  
    group Process Site A
        :Reset reliabilityScore = 0;
        :Perform PlannedDataTests;
        :Make assignment based on PlannedDataTests;
        :Update reliabilityScore;
    end group

    :Check if opposite site is reachable;

    if (Site B reachable?) then (Yes)
        group Process Site B
            :Reset reliabilityScore = 0;
            :Perform 'PlannedDataTests';
            :Make assignment based on PlannedDataTests;
            :Update reliabilityScore;
        end group


    group Cross-Link Tests
        :Perform 'Cross-Link Tests';
        :Update reliabilityScore; 
        if (reliabilityScore > thresholdValue?) then (Yes)
            :Write linkId into LTP;
            :Requeue Entry & End Process;
            stop
        else (no)
        endif

    end group

    else (no)
        if (reliabilityScore > thresholdValue?) then (Yes)
            :Write linkId into LTP;
            :Requeue Entry & End Process;
            stop
        else (no)
        endif
    endif

    :Next iteration;

end group

@enduml
