@startuml
start

:Retrieve Entry from Queue;

group for each AirInterfaceLtp in Site A
     
repeat

    group Evaluate LTP in Site A
        :Reset reliabilityScore = 0;
        :Perform PlannedDataTests;
        :Make assignment based on PlannedDataTests;
        :Update reliabilityScore;
    end group

    :Check if opposite site is reachable;
    
    if (Site B reachable?) then (Yes)

        group for each AirInterfaceLtp in Site B
        

            repeat
                group Evaluate LTP in Site B
                    :Reset reliabilityScore = 0;
                    :Perform 'PlannedDataTests';
                    :Make assignment based on PlannedDataTests;
                    :Update reliabilityScore;
                    :reliabilityScore = reliabilityScore / 2;
                end group

                group Cross-Link Tests
                    :Perform 'Cross-Link Tests';
                    :Update reliabilityScore;
                end group

                
                if (reliabilityScore > thresholdValue?) then (Yes)
                    :Write linkId into LTP;
                    :End Process with '200' and Requeue Entry;
                    stop
                else (No)
                endif

            repeat while (continue with next LTP in B)

         end group



    else (No)
        if (reliabilityScore > thresholdValue?) then (Yes)
            :Write linkId into LTP;
            :End Process with '200' and Requeue Entry;
            stop
        
        else (no)
        endif
    endif

repeat while (Continue with Next LTP in A)
-> //no more LTPs in site A//;
stop









end group

@enduml
